stages:
  - build

variables:
  FLUTTER_CHANNEL: "stable" # or "beta", "dev", etc.
  FLUTTER_VERSION: "3.0.0"  # Replace with your desired Flutter version

before_script:
  - git clone https://github.com/flutter/flutter.git --branch $FLUTTER_CHANNEL --depth 1
  - set PATH=%PATH%;%CD%\flutter\bin
  - flutter doctor
  - flutter config --enable-windows-desktop

build_windows:
  stage: build
  script:
    - flutter pub get
    - flutter build windows
  artifacts:
    paths:
      - build/windows/runner/Release/
    expire_in: 1 week
